spring:
  application:
    name: hyeja
  config:
    import: "optional:file:./.env[.properties][encoding=utf-8]"
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: ${DB_SEED_MODE:always}
      data-locations: classpath:db/seed/dev-data.sql
      encoding: UTF-8
      continue-on-error: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

server:
  port: ${SERVER_PORT:8080}

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
